### ISSUE TITLE
demo does not work-chrome@66

### ISSUE THREAD

**Issue by amitport** [appleple/scroll-hint#1]

**Comment by joshuaptfan** [comment]
I see an effect when viewing the demo as a mobile device in devtools.

If the intention is to serve only mobile devices, please say so in the documentation.

**Comment by steelydylan** [comment]
I think it is also available for pc devices.
when the screen size is small enough, then the pointer will appear.
Please make sure if the pointer shows up, when you narrow the pc screen.

**Comment by ChriStef** [comment]
It will be a nice idea to have an option to add the ability if someone wants and to desktop to show the scrollable icon!

**Comment by spartanatreyu** [comment]
Works fine on Chrome 75 for macOS 10.14.5
